[tool.pylint]
indent-string = "  "
max-args = 10
max-locals = 29
max-statements = 100
max-line-length = 160
max-attributes = 16
disable = [
  "E0401",
  "F0010",
  "W0718", # disable=broad-exception-caught
  "W0201"
]
ignore-patterns = ".*?_test.py"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 160

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
namespace_packages = false
ignore_missing_imports = true
